### ISSUE TITLE
WASTools 

### ISSUE THREAD

**Issue by HASSANTECHNO** [Simizfo/WSATools#1]
Can't install Google Play, what is the reason?

**Comment by Simizfo** [comment]
Google Play requires Play Services and a bunch of other things that need to be installed in the android system itself. it's not simply an app that can be installed like the others and you're done.

Check this out though:
[ADeltaX made a way to install the Play Store in WSA](https://www.youtube.com/watch?v=rIt00xDp0tM) 

Closing this.
