### ISSUE TITLE
problemi con l'avvio

### ISSUE THREAD

**Issue by S0n1e77a** [Simizfo/WSATools#12]
ciao, ho scaricato ieri l'app ma quando la faccio partire, appare la schermata con "scegli un APK" e quando lo premo mi va in un logging infinito, senza darmi la possibilità di inserire APK, non so se è un problema del codice o se devo attivare qualche funzione particolare.

**Comment by Simizfo** [comment]
Quasi sicuramente è il bug riportato nei ticket #2 e #11

Ti pregherei di aspettare per un fix, oppure, se ti va di smanettare a tuo rischio e pericolo, provare la soluzione proposta nel ticket #2 👍 

Grazie per la pazienza! Se vuoi aggiungere altri dettagli, per favore fallo nel thread #2. Qui chiudo, per evitare duplicati.

---

For english readers: This is a duplicate of issues #2 and #11.
