### ISSUE TITLE
App suddenly stopped working - using ADB installed by the app

### ISSUE THREAD

**Issue by freid60** [Simizfo/WSATools#14]
All was working well. Suddenly now not working. When I click "select an APK", all I get is just a page with a 
constant "loading" sign. SS in attachment
![ScreenShot 2021-12-19 135507](https://user-images.githubusercontent.com/17290561/146674086-ed8fa06e-3d97-4f9f-bf1a-54b086bca956.jpg)

**Comment by Simizfo** [comment]
Hi. Could this be the issue reported in #2 and #11?

Please check if you've installed the ADB package from XDA.

**Comment by alexoughton** [comment]
I'm seeing the same thing. I haven't installed any ADB package other than the one WSATools installs on its own, and there's nothing relevant in my PATH variable which I can see.

**Comment by Simizfo** [comment]
Interesting. There's enough reports now to understand it's actually another bug. I'll be investigating and trying to solve this before 0.2.0 ships.

Thanks for reporting!

**Comment by Simizfo** [comment]
This should be fixed, will be available when 0.2.0 releases.

Thanks for reporting!
