### ISSUE TITLE
app is blank and it keeps loading in a circle

### ISSUE THREAD

**Issue by fisforfaheem** [Simizfo/WSATools#23]
app is blank and it keeps loading in a circle

**Comment by BluestCloud** [comment]
I have the same issue. It asks for ADB to install and I select the folder to install it, then asks for the apk and I gave it the tiktok apk. Then it just hangs with loading in a circle.

**Comment by Simizfo** [comment]
This is issue #11. Fix coming in the next release, that's happening soon. I had to put development aside, now I'm back at it.
