### ISSUE TITLE
Stuck on "Installing application" and nothing happens

### ISSUE THREAD

**Issue by Ahmed-Elrayes** [Simizfo/WSATools#26]
Hello, i've a little issue.
whenever i select an apk to install it keeps stuck on installing the package 
as you can see in the image below 
![Image 1](https://user-images.githubusercontent.com/30704271/155845051-2b260b09-d04c-4f71-a7c3-9067ffe8894b.png)

i got the android sub system, and developer tools is enabled...
Thanks in advance

**Comment by Simizfo** [comment]
Next version has more complete logging in case of errors like this one. Please wait for the update and report what happens, thanks!

**Comment by Ahmed-Elrayes** [comment]
yeah sure, thanks a lot

**Comment by Simizfo** [comment]
WSATools 0.1.80 is now out, please update, try it again and see if it still gets stuck or if you get an error.
Let me know, please!

Thank you for waiting.

**Comment by luke-uppx** [comment]
Hi, my first installation went well but I don't understand now why it is stucked

**Comment by Simizfo** [comment]
Nice!
I've made some more improvements on this for 0.2.0, so I'm keeping this open until that version releases.

**Comment by Ahmed-Elrayes** [comment]
it's working just fine for me, thanks a lot.

**Comment by Simizfo** [comment]
Closing this as it's solved!

**Comment by DeViL-CU** [comment]
Hello, I present the same problem, every time I select an APK to install, it stays stuck in the installation of the package and does not pass, I have version 0.2.5 of WSATools installed

![Captura de pantalla 2023-02-12 174657](https://user-images.githubusercontent.com/36394189/218344581-71dcdc9f-4c5d-4f0d-bec5-5e7dce00be80.png)

I have the Android subsystem and the development tools are enabled...
Thanks in advance
