### ISSUE TITLE
ADB writes install details to stderr, making WSATools report a fake error

### ISSUE THREAD

**Issue by whitefcy** [Simizfo/WSATools#29]
![image](https://user-images.githubusercontent.com/89247461/156326146-e5d02362-20fa-43e8-9f43-3546e62dec5b.png)

**Comment by whitefcy** [comment]
> Oh god. Install details get written to stderr?
> 
> Thanks for reporting...
> 
> The app should be installed anyway, right?

It failed 😭

**Comment by Simizfo** [comment]
Hm. Can you please tell me what APK were you trying to install?

**Comment by Simizfo** [comment]
Works fine here 🤔 

So it's some other kind of error you're getting and it's actually legit, but WSATools doesn't show it entirely. In the past this was the "unlimited loading" error that some people had. I'm doing small steps into finding out what happens. Will improve logging by the next version 👍 thanks for reporting

**Comment by Simizfo** [comment]
This works fine now, I think I forgot to close this issue.
