### ISSUE TITLE
Microsoft Store link broken

### ISSUE THREAD

**Issue by StormProductionsMusic** [Simizfo/WSATools#3]
Hi,

I can't seem to be able to download the app, as the Microsoft Store link you provided in the readme seems to be broken.

Please provide a direct link to download it for now until this gets resolved.

Thanks.

**Comment by Simizfo** [comment]
Hi there! 

Can you please explain better what happens?
You click on the link and...?

Asking because it works fine here, so I need more details to understand.

Thanks!

**Comment by StormProductionsMusic** [comment]
Hi,

I have no information to give anymore, as it got fixed by itself. 
Basically what happens sometimes, after updates of Windows, is that network on Google apps doesn't work and I have to restart my PC a few times to get it fixed. 

Also, how do I actually update the WSA when there are new updates? Microsoft Store doesn't detect updates on it as it's modified.

**Comment by Simizfo** [comment]
I guess you should download the original update version, and then apply the mods over it. Yeah, every time.

Closing this as it's solved. Thanks!
