### ISSUE TITLE
Feature Proposal: Add ability to install XAPK files

### ISSUE THREAD

**Issue by Simizfo** [Simizfo/WSATools#32]
This has been requested over Twitter, app reviews on the Microsoft Store and DMs.

WSATools would be able to recognize if the file is an APK bundle and install it accordingly.

Please comment on this post to show interest in this feature, so I can give the right priority to all features to implement.

**Comment by Grossley** [comment]
I am in favor of this feature and would like it included with the tool.

**Comment by viruscamp** [comment]
If we wanna install an app from google appstore, we can use apkpure.com, but most recent apps are in xapk format.

As I know https://github.com/alesimula/wsa_pacman has this feature already.

**Comment by Simizfo** [comment]
Project is on hold until 14/07, I'm currently getting my degree done. Expect me to get back working on it! This will definitely be implemented.

**Comment by Simizfo** [comment]
This is now available! Enjoy!

**Comment by sonofwatt** [comment]
An .xapk file downloaded from apkpure has WSATools saying it "can't read this APK info". 
Is this expected behaviour for some .xapk files?

**Comment by Simizfo** [comment]
Hi there @sonofwatt . Some APK bundles are made in different ways, and while WSATools should be able to install any kind of bundle, it can't always read the informations correctly.

Would you mind to open another Issue and share that XAPK, so I can understand what's wrong and fix it? Thanks!
