### ISSUE TITLE
wsa tools app loading problem

### ISSUE THREAD

**Issue by abrar-bajwa** [Simizfo/WSATools#49]
I have installed an app using wsa tools but when i open an app it keeps loading. pls kindly help me solve this.
<img width="960" alt="1" src="https://user-images.githubusercontent.com/76744955/232234573-b8db58ff-42a8-4fd9-b499-40af3b0d65e1.png">

**Comment by Simizfo** [comment]
I'm sorry, but this has nothing to do with WSATools at all. This is a WSA issue, or an app issue.

WSATools is an app installer, it doesn't run them.
