### ISSUE TITLE
Closing the filepicker closes the app

### ISSUE THREAD

**Issue by MarcAnt01** [Simizfo/WSATools#5]
If you close the file picker without selecting any file the app crashes

**Comment by Simizfo** [comment]
The app doesn't crash, it quits because I chose so. 

If you don't pick an APK, what do you want the app to do? 🤔 This might change, of course, if there's something that makes more sense

**Comment by MarcAnt01** [comment]
In the current design, actually it makes sense, but as you've said in another ticket if you plan to add more settings, user might want to a change a setting before installing an apk and this isn't really expected

**Comment by Simizfo** [comment]
In that case I'll change it, yeah. Makes sense!

**Comment by Simizfo** [comment]
Version 0.2.0 (will be released as soon as possible) has a totally new navigation system, so this behavior isn't a thing anymore.

Closing!
