### ISSUE TITLE
Error when installing an APK

### ISSUE THREAD

**Issue by davegr2022** [Simizfo/WSATools#50]
Hola me sale el siguiente mensaje y no se que hacer, ayuda please.
![image](https://github.com/Simizfo/WSATools/assets/91983152/5722d9b5-6948-4b32-be7d-f15a9ee2a85b)

**Comment by Simizfo** [comment]
Podría enviar los registros de la aplicación? Puede encontrarlos en la página principal de la aplicación. Gracias!

Also, if you could write in english that would be really better, thanks :D That would prevent me from using a translator and butchering a language

**Comment by davegr2022** [comment]
![image](https://github.com/Simizfo/WSATools/assets/91983152/e9ad54ce-b6da-4e5f-8d5a-e9dc2b8f4ecd)

**Comment by Simizfo** [comment]
Have you followed the guide linked in the error?
![image](https://github.com/Simizfo/WSATools/assets/29689637/775bca7c-4758-4326-ace2-549e3c1fc1a7)

**Comment by davegr2022** [comment]
If you already tried that, reinstall adb on C: and probe install with WSATools other apk of Netflix
![image](https://github.com/Simizfo/WSATools/assets/91983152/7c0fcff4-1365-4cce-ae65-d8975d8e8f70)
![image](https://github.com/Simizfo/WSATools/assets/91983152/0c059eb7-5edd-4868-b43c-50509d8eee89)
![image](https://github.com/Simizfo/WSATools/assets/91983152/8b2fd57d-696e-4404-bf10-439010885339)

**Comment by Simizfo** [comment]
> ![image](https://user-images.githubusercontent.com/91983152/239583466-7c0fcff4-1365-4cce-ae65-d8975d8e8f70.png) 

This is the wrong place. You should enable the developer mode inside the Windows Subsystem for Android app, not in Windows Settings.

<img width="914" alt="image" src="https://github.com/Simizfo/WSATools/assets/29689637/09e8fa31-98cf-48a6-9f87-0186afb22fa8">

**Comment by davegr2022** [comment]
Thanks, that was the problem. you already solved it

**Comment by Simizfo** [comment]
You're welcome! Thanks for using my app!

Closing.
