### ISSUE TITLE
Getting an error while installing an apk file

### ISSUE THREAD

**Issue by CodeSudo** [Simizfo/WSATools#51]
![Screenshot 2023-05-20 123318](https://github.com/Simizfo/WSATools/assets/58101085/ea3ddccb-afd6-42b4-94e5-9d2570c09f33)
![Screenshot 2023-05-20 123335](https://github.com/Simizfo/WSATools/assets/58101085/d6d5b4c1-b4fe-40ce-b967-f9ffcc98b5c4)
![Screenshot 2023-05-20 123651](https://github.com/Simizfo/WSATools/assets/58101085/1fba9f60-55ab-4289-94bf-00aba76796dd)

**Comment by Simizfo** [comment]
Hi, could you send your WSATools logs? You can find them in the app main page. Thanks!

**Comment by CodeSudo** [comment]
**Sure here is the entire log **

CORE: Checking for WSA...
CORE: Checking for WSA returned 0
CORE: Checking for WSA...
CORE: Checking for WSA returned 0
CORE: Checking for WSA...
CORE: Checking for WSA returned 0
CORE: Checking for ADB...
CORE: ADB Found - Installed by WSATools - D:\New folder
CORE: Preparing APK at C:\Users\Prade\Downloads\studytalk.apk
CORE: Preparing APK encountered an error: Could not find any recognizable digits.
CORE: Checking for WSA...
CORE: Checking for WSA returned 0
CORE: Checking for WSA...
CORE: Checking for WSA returned 0
CORE: Checking for ADB...
CORE: ADB Found - Installed by WSATools - D:\New folder
CORE: Preparing APK at C:\Users\Prade\Downloads\Telegram Desktop\app-release.apk
CORE: Preparing APK encountered an error: Could not find any recognizable digits.
CORE: Attempting connection to WSA - Attempt n 1 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 2 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 3 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 4 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 5 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 6 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 7 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 8 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 9 (Max 10)
CORE: Connection Timeout
CORE: Attempting connection to WSA - Attempt n 10 (Max 10)
CORE: Connection Timeout
CORE: Installing APK at C:\Users\Prade\Downloads\Telegram Desktop\app-release.apk
INSTALL: Performing Push Install
INSTALL: adb: error: failed to get feature set: device 'localhost:58526' not found

**Comment by Simizfo** [comment]
Thanks! Have you followed the guide that is reported in the error? If you have already enabled ADB debugging/developer mode in the Windows Subsystem for Android Settings app, then try to follow that guide and reset it

Thanks!

**Comment by CodeSudo** [comment]
Worked! Thank you😊

**Comment by Simizfo** [comment]
You're welcome!
