### ISSUE TITLE
Hidden buttons are navigable 

### ISSUE THREAD

**Issue by MarcAnt01** [Simizfo/WSATools#6]
If you use tab in the app, the hidden buttons in the home screen are shown, also for the one on the left the focus seems to be set on it
![image](https://user-images.githubusercontent.com/43090263/144137723-9e0401f0-954c-463b-a889-02d97c22f1fc.png)
![image](https://user-images.githubusercontent.com/43090263/144137581-32880f5e-0877-4dd9-bc0e-365cffc0fef6.png)

**Comment by Simizfo** [comment]
oops, will fix this

**Comment by jamesmcroft** [comment]
Just bringing comment over from #27. If you hit enter on the first (believe this is install), it will crash the application.

**Comment by Simizfo** [comment]
Yup. Next version has almost all pages reorganized and cleaned up, so this won't happen anymore. Will close this issue once it's out.

Thanks!

**Comment by Simizfo** [comment]
Solved in 0.1.80, thanks!
