### ISSUE TITLE
can't open xapk

### ISSUE THREAD

**Issue by RdwnBut** [Simizfo/WSATools#60]
I can't open xapk file. I want to install Azur lane, but i got this
![Screenshot 2023-09-13 021857](https://github.com/Simizfo/WSATools/assets/82056888/84bc9d5f-13f0-4c82-9e81-11f0a61c2a81)

**Comment by Simizfo** [comment]
This is a bit late, sorry.

But you can try and do "install anyway" **only if you know** where your APK bundle comes from is a safe place.

Closing since it's not really a bug.
