### ISSUE TITLE
i can't restore after fresh windows install

### ISSUE THREAD

**Issue by midonasser** [Simizfo/WSATools#62]
![Screenshot 2023-09-14 093843](https://github.com/Simizfo/WSATools/assets/84553717/6705a2b2-49ca-44c0-90b8-adf188ca14a0)

**Comment by Simizfo** [comment]
Hi, thanks for reporting. Microsoft has done some changes to how WSA works so the Backups feature is currently broken.

Once I get some time I'll try to fix it.

Closing this as it's duplicate and already been reported in #59. Please check that issue for updates.
