### ISSUE TITLE
Can't install apps. "device unauthorized"

### ISSUE THREAD

**Issue by TacoRaptor67** [Simizfo/WSATools#63]
As far as I know I meet all of the requirements. I'm running Windows 11, I've installed the Windows Subsystem for Android app, and Developer Mode is on with Continuous selected. This is all that happens with every single app that I try.
![Error](https://github.com/Simizfo/WSATools/assets/46816918/0a2de751-ceaa-4f2e-8c31-aaa313bbec6f)
I tried what's suggested in the guide, but still the same issue occurs. What's strange is I never get a popup asking for authorization like the guide says I will.

**Comment by TacoRaptor67** [comment]
Never mind! I was explaining the issue to a friend, trying it again, and it asked permission. I checked "Always allow from this computer" and hit Allow, and everything is fine now. Can't figure out for the life of me why it never asked before or why it did now... but oh well.

**Comment by Simizfo** [comment]
Thank you for your report, I am happy that you were able to solve your issue. Sadly there's no way to automate this.

Closing this.
