### ISSUE TITLE
Backup can't be restored, see attached screenshot

### ISSUE THREAD

**Issue by wonkxin** [Simizfo/WSATools#70]
![WSAtools_BackupRestore_Error](https://github.com/Simizfo/WSATools/assets/49319011/c4302a28-2251-45dd-a798-067f5fa528ed)

@https://github.com/Simizfo/WSATools/issues/59
After renaming userdata.2.vhdx to userdata.vhdx for the restore process, the backup could be restored, but after that, the apps didn't appear in WSA/Apps

**Comment by binaryn3xus** [comment]
I get this similar error trying to do a backup

**Comment by Simizfo** [comment]
Hi there. Backups aren't working anymore due to a change that Microsoft made to WSA.

I still haven't had time in these last months to make a fix. Sorry about that.

**Comment by Simizfo** [comment]
Closing, this is a duplicate of #59, check that issue for updates.
